--agregando consultas de inserción de registros en cada tabla min.3

--INGRESO DE DATOS DE USUARIO


--INGRESO DE DATOS DE CLIENTE


--INGRESO DE DATOS DE CAPACITACION


--INGRESO DE DATOS DE ASISTENTES


--INGRESO DE DATOS DE VISITA
INSERT INTO VISITA (IDVISITA, VISFECHA, VISHORA, VISLUGAR, VISCOMENTARIOS, CLIENTE_RUTCLIENTE) 
VALUES ('111', TO_DATE('2021-02-21', 'YYYY-MM-DD'), TO_DATE('09:30:00', 'HH24:MI:SS'), 'Providencia', 'inspeccion', '770011');
INSERT INTO VISITA (IDVISITA, VISFECHA, VISHORA, VISLUGAR, VISCOMENTARIOS, CLIENTE_RUTCLIENTE) 
VALUES ('222', TO_DATE('2021-02-22', 'YYYY-MM-DD'), TO_DATE('09:30:00', 'HH24:MI:SS'), 'La Florida', 'inspeccion', '772233');
INSERT INTO VISITA (IDVISITA, VISFECHA, VISHORA, VISLUGAR, VISCOMENTARIOS, CLIENTE_RUTCLIENTE) 
VALUES ('333', TO_DATE('2021-02-23', 'YYYY-MM-DD'), TO_DATE('09:30:00', 'HH24:MI:SS'), 'La Reina', 'inspeccion', '774466');

--INGRESO DE DATOS DE CHEQUEO
INSERT INTO CHEQUEO (IDCHEQUEO, NOMBRE, DETALLE) VALUES ('20211', 'Norma 1', 'revisar cumplimiento');
INSERT INTO CHEQUEO (IDCHEQUEO, NOMBRE, DETALLE) VALUES ('20212', 'Norma 2', 'revisar cumplimiento');
INSERT INTO CHEQUEO (IDCHEQUEO, NOMBRE, DETALLE) VALUES ('20213', 'Norma 3', 'revisar cumplimiento');

--INGRESO DE DATOS DE REGISTROCHEQUEO
INSERT INTO REGISTROCHEQUEO (VISITA_IDVISITA, CHEQUEO_IDCHEQUEO, ESTADO) VALUES ('111', '20211', '1');
INSERT INTO REGISTROCHEQUEO (VISITA_IDVISITA, CHEQUEO_IDCHEQUEO, ESTADO) VALUES ('111', '20211', '1');
INSERT INTO REGISTROCHEQUEO (VISITA_IDVISITA, CHEQUEO_IDCHEQUEO, ESTADO) VALUES ('111', '20211', '1');

--INGRESO DE DATOS DE ACCIDENTE
INSERT INTO ACCIDENTE (IDACCIDENTE, ACCIFECHA, ACCIHORA, ACCILUGAR, ACCIORIGEN, ACCICONSECUENCIAS, CLIENTE_RUTCLIENTE) 
VALUES ('111', TO_DATE('2021-02-25', 'YYYY-MM-DD'), TO_DATE('11:30:00', 'HH24:MI:SS'), 'TRABAJO', 'CAIDA', 'LESION LEVE', '770011');
INSERT INTO ACCIDENTE (IDACCIDENTE, ACCIFECHA, ACCIHORA, ACCILUGAR, ACCIORIGEN, ACCICONSECUENCIAS, CLIENTE_RUTCLIENTE) 
VALUES ('222', TO_DATE('2021-02-26', 'YYYY-MM-DD'), TO_DATE('09:45:00', 'HH24:MI:SS'), 'TRANSCURSO AL TRABAJO', 'CAIDA', 'FRACTURA', '772233');
INSERT INTO ACCIDENTE (IDACCIDENTE, ACCIFECHA, ACCIHORA, ACCILUGAR, ACCIORIGEN, ACCICONSECUENCIAS, CLIENTE_RUTCLIENTE) 
VALUES ('333', TO_DATE('2021-02-27', 'YYYY-MM-DD'), TO_DATE('16:30:00', 'HH24:MI:SS'), 'FUERA DEL TRABAJO', 'CHOQUE', 'LESION GRAVE', '774466');

--INGRESO DE DATOS DE ADMINISTRATIVO
INSERT INTO ADMINISTRATIVO (RUNADMINISTRATIVO, ADCORREO, ADAREA, USUARIO_RUNUSUARIO) VALUES ('115566', 'A1@GMAIL.COM', 'INFORMATICA', '115566');
INSERT INTO ADMINISTRATIVO (RUNADMINISTRATIVO, ADCORREO, ADAREA, USUARIO_RUNUSUARIO) VALUES ('116655', 'A2@GMAIL.COM', 'LOGISTICA', '116655');
INSERT INTO ADMINISTRATIVO (RUNADMINISTRATIVO, ADCORREO, ADAREA, USUARIO_RUNUSUARIO) VALUES ('117744', 'A3@GMAIL.COM', 'DESARROLLO', '117744');

--INGRESO DE DATOS DE PROFESIONAL

--INGRESO DE DATOS DE ASESORIAS

--INGRESO DE DATOS DE MEJORAS

--INGRESO DE DATOS DE PAGOS
INSERT INTO PAGO (PAGFECHA, PAGMONTO, PAGMES, PAGANYO, CLIENTE_RUTCLIENTE) 
VALUES (TO_DATE('2021-02-21 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), '100000', '03', '2021', '770011');
INSERT INTO PAGO (PAGFECHA, PAGMONTO, PAGMES, PAGANYO, CLIENTE_RUTCLIENTE) 
VALUES (TO_DATE('2021-02-21 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), '200000', '04', '2021', '772233');
INSERT INTO PAGO (PAGFECHA, PAGMONTO, PAGMES, PAGANYO, CLIENTE_RUTCLIENTE) 
VALUES (TO_DATE('2021-02-21 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), '300000', '05', '2021', '774466');
 